# Generated by Django 5.1 on 2024-08-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articls',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
